{"content":"<div><div class=\"content\">\n<p>The C# language&#39;s exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running. Exception handling uses the <code>try</code>, <code>catch</code>, and <code>finally</code> keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward. Exceptions can be generated by the common language runtime (CLR), by the .NET Framework or any third-party libraries, or by application code. Exceptions are created by using the <code>throw</code> keyword.  </p>\n<p> In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack. When this happens, the CLR will unwind the stack, looking for a method with a <code>catch</code> block for the specific exception type, and it will execute the first such <code>catch</code> block that if finds. If it finds no appropriate <code>catch</code> block anywhere in the call stack, it will terminate the process and display a message to the user.  </p>\n<p> In this example, a method tests for division by zero and catches the error. Without the exception handling, this program would terminate with a <strong>DivideByZeroException was unhandled</strong> error.  </p>\n<pre><code class=\"lang-cs\" name=\"csProgGuideExceptions#18\">    class ExceptionTest\n    {\n        static double SafeDivision(double x, double y)\n        {\n            if (y == 0)\n                throw new System.DivideByZeroException();\n            return x / y;\n        }\n        static void Main()\n        {\n            // Input for test purposes. Change the values to see\n            // exception handling behavior.\n            double a = 98, b = 0;\n            double result = 0;\n\n            try\n            {\n                result = SafeDivision(a, b);\n                Console.WriteLine(&quot;{0} divided by {1} = {2}&quot;, a, b, result);\n            }\n            catch (DivideByZeroException e)\n            {\n                Console.WriteLine(&quot;Attempted divide by zero.&quot;);\n            }\n        }\n    }\n</code></pre><h2 id=\"exceptions-overview\">Exceptions Overview</h2>\n<p> Exceptions have the following properties:  </p>\n<ul>\n<li><p>Exceptions are types that all ultimately derive from <code>System.Exception</code>.  </p>\n</li>\n<li><p>Use a <code>try</code> block around the statements that might throw exceptions.  </p>\n</li>\n<li><p>Once an exception occurs in the <code>try</code> block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack. In C#, the <code>catch</code> keyword is used to define an exception handler.  </p>\n</li>\n<li><p>If no exception handler for a given exception is present, the program stops executing with an error message.  </p>\n</li>\n<li><p>Do not catch an exception unless you can handle it and leave the application in a known state. If you catch <code>System.Exception</code>, rethrow it using the <code>throw</code> keyword at the end of the <code>catch</code> block.  </p>\n</li>\n<li><p>If a <code>catch</code> block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.  </p>\n</li>\n<li><p>Exceptions can be explicitly generated by a program by using the <code>throw</code> keyword.  </p>\n</li>\n<li><p>Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.  </p>\n</li>\n<li><p>Code in a <code>finally</code> block is executed even if an exception is thrown. Use a <code>finally</code> block to release resources, for example to close any streams or files that were opened in the <code>try</code> block.  </p>\n</li>\n<li><p>Managed exceptions in the .NET Framework are implemented on top of the Win32 structured exception handling mechanism. For more information, see <a href=\"https://docs.microsoft.com/cpp/cpp/structured-exception-handling-c-cpp\" data-linktype=\"external\">Structured Exception Handling (C/C++)</a> and <a href=\"http://go.microsoft.com/fwlink/?LinkId=119654\" data-linktype=\"external\">A Crash Course on the Depths of Win32 Structured Exception Handling</a>.  </p>\n</li>\n</ul>\n<h2 id=\"related-sections\">Related Sections</h2>\n<p> See the following topics for more information about exceptions and exception handling:  </p>\n<ul>\n<li><p><a href=\"using-exceptions\" data-linktype=\"relative-path\">Using Exceptions</a>  </p>\n</li>\n<li><p><a href=\"exception-handling\" data-linktype=\"relative-path\">Exception Handling</a>  </p>\n</li>\n<li><p><a href=\"creating-and-throwing-exceptions\" data-linktype=\"relative-path\">Creating and Throwing Exceptions</a>  </p>\n</li>\n<li><p><a href=\"compiler-generated-exceptions\" data-linktype=\"relative-path\">Compiler-Generated Exceptions</a>  </p>\n</li>\n<li><p><a href=\"how-to-handle-an-exception-using-try-catch\" data-linktype=\"relative-path\">How to: Handle an Exception Using try/catch (C# Programming Guide)</a>  </p>\n</li>\n<li><p><a href=\"how-to-execute-cleanup-code-using-finally\" data-linktype=\"relative-path\">How to: Execute Cleanup Code Using finally</a>  </p>\n</li>\n</ul>\n<h2 id=\"c-language-specification\">C# Language Specification</h2>\n<p> For more information, see the <a href=\"../../language-reference/language-specification\" data-linktype=\"relative-path\">C# Language Specification</a>. The language specification is the definitive source for C# syntax and usage.  </p>\n<h2 id=\"see-also\">See Also</h2>\n<p> <a class=\"xref\" href=\"../../../../api/system.systemexception\" data-linktype=\"relative-path\">SystemException</a><br> <a href=\"../index\" data-linktype=\"relative-path\">C# Programming Guide</a><br> <a href=\"../../language-reference/keywords/index\" data-linktype=\"relative-path\">C# Keywords</a><br> <a href=\"../../language-reference/keywords/throw\" data-linktype=\"relative-path\">throw</a><br> <a href=\"../../language-reference/keywords/try-catch\" data-linktype=\"relative-path\">try-catch</a><br> <a href=\"../../language-reference/keywords/try-finally\" data-linktype=\"relative-path\">try-finally</a><br> <a href=\"../../language-reference/keywords/try-catch-finally\" data-linktype=\"relative-path\">try-catch-finally</a><br> <a href=\"http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735\" data-linktype=\"external\">Exceptions</a><br> <a href=\"http://msdn.microsoft.com/library/f7d68675-be06-40fb-a555-05f0c5a6f66b\" data-linktype=\"external\">Exception Hierarchy</a><br> <a href=\"http://go.microsoft.com/fwlink/?LinkId=112400\" data-linktype=\"external\">Writing Reliable .NET Code</a><br> <a href=\"http://go.microsoft.com/fwlink/?LinkId=112408\" data-linktype=\"external\">Minidumps for Specific Exceptions</a></p>\n</div></div>","outputRootRelativePath":"../../../../","pageMetadata":"<meta name=\"author\" content=\"BillWagner\">\r\n<meta name=\"ms.author\" content=\"wiwagn\">\r\n<meta name=\"manager\" content=\"wpickett\">\r\n<meta name=\"breadcrumb_path\" content=\"/dotnet/toc2.json\">\r\n<meta name=\"ms.assetid\" content=\"0001887f-4fa2-47e2-8034-2819477e2344\">\r\n<meta name=\"translation.priority.ht\" content=\"cs-cz\">\r\n<meta name=\"translation.priority.ht\" content=\"de-de\">\r\n<meta name=\"translation.priority.ht\" content=\"es-es\">\r\n<meta name=\"translation.priority.ht\" content=\"fr-fr\">\r\n<meta name=\"translation.priority.ht\" content=\"it-it\">\r\n<meta name=\"translation.priority.ht\" content=\"ja-jp\">\r\n<meta name=\"translation.priority.ht\" content=\"ko-kr\">\r\n<meta name=\"translation.priority.ht\" content=\"pl-pl\">\r\n<meta name=\"translation.priority.ht\" content=\"pt-br\">\r\n<meta name=\"translation.priority.ht\" content=\"ru-ru\">\r\n<meta name=\"translation.priority.ht\" content=\"tr-tr\">\r\n<meta name=\"translation.priority.ht\" content=\"zh-cn\">\r\n<meta name=\"translation.priority.ht\" content=\"zh-tw\">\r\n<meta name=\"caps.latest.revision\" content=\"33\">\r\n<meta name=\"ms.topic\" content=\"article\">\r\n<meta name=\"ms.date\" content=\"2015-07-20\">\r\n<meta name=\"ms.technology\" content=\"devlang-csharp\">\r\n<meta name=\"ms.prod\" content=\".net\">\r\n<meta name=\"search.ms_sitename\" content=\"Docs\">\r\n<meta name=\"search.ms_docsetname\" content=\"docs-internal\">\r\n<meta name=\"version\" content=\"0\">\r\n<meta name=\"locale\" content=\"en-us\">\r\n<meta name=\"site_name\" content=\"Docs\">\r\n<meta name=\"search.ms_product\" content=\"MSDN\">\r\n<meta name=\"depot_name\" content=\"MSDN.docs-internal\">\r\n<meta name=\"updated_at\" content=\"2017-03-15 06:14 PM\">\r\n<meta name=\"gitcommit\" content=\"https://github.com/dotnet/docs-internal/blob/3115359729431ecbcc16058612da59b85621fa0f/docs/csharp/programming-guide/exceptions/index.md\">\r\n<meta name=\"original_content_git_url\" content=\"https://github.com/dotnet/docs-internal/blob/master/docs/csharp/programming-guide/exceptions/index.md\">\r\n<meta name=\"document_id\" content=\"46731983-828b-7ef9-9666-912443224e85\">\r\n<meta name=\"pagetype\" content=\"Conceptual\">\r\n<meta name=\"toc_rel\" content=\"toc2.json\">\r\n","rawMetadata":{"author":"BillWagner","ms.author":"wiwagn","manager":"wpickett","breadcrumb_path":"/dotnet/toc.json","title":"Exceptions and Exception Handling (C# Programming Guide) | Microsoft Docs","ms.assetid":"0001887f-4fa2-47e2-8034-2819477e2344","translation.priority.ht":["cs-cz","de-de","es-es","fr-fr","it-it","ja-jp","ko-kr","pl-pl","pt-br","ru-ru","tr-tr","zh-cn","zh-tw"],"caps.latest.revision":33,"ms.topic":"article","dev_langs":["csharp"],"helpviewer_keywords":["exception handling [C#]","exceptions [C#]","C# language, exceptions"],"ms.date":"2015-07-20","ms.technology":["devlang-csharp"],"ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"_op_canonicalUrlPrefix":"https://docs.microsoft.com/en-us/dotnet-internal/","locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","_op_openToPublicContributors":false,"depot_name":"MSDN.docs-internal","_op_gitCommitHistory":[{"author_name":"Bill Wagner","author_email":"wiwagn@microsoft.com","committer_name":"GitHub","comitter_email":"noreply@github.com","message":"Reorganize the C# Guide TOC (#1318)","commit_sha":"3115359729431ecbcc16058612da59b85621fa0f","commit_date":"2017-01-23 23:20:14 -0500"}],"updated_at":"2017-03-15 06:14 PM","_op_gitContributorInformation":{"author":{"profile_url":"https://github.com/BillWagner","display_name":"Bill Wagner","id":"493969"},"contributors":[{"profile_url":"https://github.com/BillWagner","display_name":"Bill Wagner"}],"update_at":"3/15/2017"},"gitcommit":"https://github.com/dotnet/docs-internal/blob/3115359729431ecbcc16058612da59b85621fa0f/docs/csharp/programming-guide/exceptions/index.md","original_content_git_url":"https://github.com/dotnet/docs-internal/blob/master/docs/csharp/programming-guide/exceptions/index.md","open_to_public_contributors":false,"content_git_url":"https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/index.md","document_id":"46731983-828b-7ef9-9666-912443224e85","layout":"Conceptual","pagetype":"Conceptual","canonical_url":"https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/exceptions/index","toc_asset_id":"articles/csharp/programming-guide/exceptions/toc.json","toc_rel":"toc.json","_op_ogTitle":"Exceptions and Exception Handling (C# Programming Guide)","_op_displayDate":null,"_op_displayDate_source":null,"_op_wordCount":615,"_op_rawTitle":"<h1 id=\"exceptions-and-exception-handling-c-programming-guide\" sourcefile=\"docs/csharp/programming-guide/exceptions/index.md\" sourcestartlinenumber=\"38\" sourceendlinenumber=\"38\">Exceptions and Exception Handling (C# Programming Guide)</h1>","_op_searchScope":[".NET"],"_op_canonicalUrl":"https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/exceptions/index","fileRelativePath":"articles/csharp/programming-guide/exceptions/index.html"},"themesRelativePathToOutputRoot":"_themes/"}